### ISSUE TITLE
Not related to this repo but your website is down

### ISSUE THREAD

**Issue by Thomashighbaugh** [K4rakara/kuudere#4]
the site listed on your profile is down, letting you know for the same reason I hope someone would do the same for me if it ever occurred. #paying-it-forward #please-dont-shoot-me-at-the-end

**Comment by K4rakara** [comment]
Yeah, its been down for a while. Doing some renovations to my basement, so I don't have anywhere to put my webserver, nor the funds to put it on a VPS at the moment. I really appreciate the gesture!

**Comment by Thomashighbaugh** [comment]
If it relatively simple, or could be made that way with a static site generator, check out Vercel. I host most of my site's with them and have had none of the problems I had with netlify and never paid a dime even hosting sites with custom urls (that I bought elsewhere). 

But I use static site generators for such and understand not everyone's site is easily bent around that workflow and all. 

Hey anytime, you do great work that I have benefited from so its the least I could do.
